### PR TITLE
Remove Staticman

### LINKED ISSUE #7: BUG: Staticman reCAPTCHA Error
# Bug Report
## Describe the bug

Staticman V2 was not working due to an issue with request limits. Was upgraded to v3 and now it has a reCAPTCHA error even when disabled.

## To Reproduce
1. Submit a comment via Staticman

## Expected behavior

Comment should successfully post
##Screenshots

## Environment
 - **Hugo Version:** 0.50
 - **Browser and Version:** 
 - **Platform:** 
 - **Link to Project: **

## Additional context

See eduardoboucas/staticman#243

### PR DESCRIPTION
**Pull request by pacollins**
## Description

Removal of all references to Staticman. 

## Motivation and Context

Staticman is dead and has been for awhile. No reason to support it at this time. I would like some sort of feedback before merging this. eduardoboucas/staticman#243

Through a waterfall effect, this closes #7.

## How Has This Been Tested?

**Hugo Version:** 0.50

**Browser(s):** Chrome

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [code style] of this project.
- [X] My change requires a change to the [documentation].
- [X] I have updated the documentation, including `theme.toml`, accordingly.
- [X] I have read the [Contributing Document].

[Code Style]: https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md#Style-Guide
[Contributing Document]: https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md
[Documentation]: https://github.com/pacollins/hugo-future-imperfect-slim/wiki

### CODE REVIEW

**Comment by VincentTam** [comment]
> Staticman is dead and has been for awhile. No reason to support it at this time. I would like some sort of feedback before merging this. eduardoboucas/staticman#243

Hi, this is the collaborator of [Hugo Swift Theme](https://github.com/onweru/hugo-swift-theme), and the maintainer of @staticmanlab, a public GitLab instance of Staticman.  You see from the linked GitHub bot's activities and from an array of [Staticman demo sites on Framagit](https://framagit.org/staticman-gitlab-pages) that Staticman v3's URL scheme suggested in eduardoboucas/staticman#219 is actually working.

**Comment by pacollins** [comment]
Thanks, I'll read through there and update the theme appropriately (or feel
free to make a PR that holds everything correctly). I couldn't get it to
work for the longest.

**Comment by VincentTam** [comment]
I don't (and I won't) know how Staticman v3 works with GitHub Apps, which is a proprietary technology that won't interest much evangelical free software users.  However, the Node.JS app itself after PR219 and before PR243 works well with custom GitLab instance like Framagit.

I'm sorry that I lack time to make a PR, but the official API instance failure doens't necessarily imply a bug in the Node.JS app or an error in the theme's Staticman integration.  There's no need to remove the later due to the former.

**Comment by pacollins** [comment]
Essentially, my motivation is that a user should be able to serve this theme with minimal set-up. This means  using a public instance like Staticman v2 was. It is my understanding that `api.staticman.com/v2` and `api.staticman.com/v3` are both inoperable, and I was unable to get the Staticman Github app to function.

If you are implying that `https://staticman-frama.herokuapp.com` is a replacement for this and it functions properly, then I would adjust the theme appropriately.

If you are implying that the user needs to create their own instance of Staticman, that is beyond the scope of what they theme should include and becomes bloat. I would rather have that as an "add-on" in a separate repository as things you can implement at the site level rather than the theme level.

**Comment by VincentTam** [comment]
Your motiviation echoes that of the author of [Beautiful Jekyll](https://github.com/daattali/beautiful-jekyll/#staticman-comments), which has incorporated my port of Minimal Mistake's Staticman integration.

Just like many big projects, users may either build their own API instance, or choose any existing public instances.  Many users choose the official one, but it's reported in https://github.com/eduardoboucas/staticman/pull/285 that the official one is not quite stable due to unnotified upgrades.  To avoid that, I suggest using an alternative API instance.  By saying "alternative", it simply means "anything but official".  It can be custom-built, an existing third-party one, etc.

What I'm suggesting is Minimal Mistake's approach: add an additional parameter in the site config file to allow specifying a custom Staticman API instance, with a default value to a currently working instance.

P.S. Having suggested the adoption of an alternative API instance, I have to mention that I've built @staticmanlab, as my user bio reads.

**Comment by pacollins** [comment]
Thanks for that clarification. That is what I was looking for. My assumption based on your comment was that I should just leave it and then users could just host their own version, which would be annoying to people looking at the theme as an "out-of-the-box" solution.

I will look into your version. I love Staticman and hated that the official ran into issues.

**Comment by VincentTam** [comment]
Perhaps it would be helpful to provide some technical details of my testing instances created to avoid possible setup errors.  I've created the 2nd one in response to [a Framagit user's failure to integrate Staticman](https://framagit.org/Bridouz/bridouz.frama.io/commit/f01aca4e3267d87d15057ca596554b3a190bd45f).

* * *
(copied from [my related comment on Framagit](https://framagit.org/kbf/novus/issues/11#note_413206))

AFAIK, the `gitlabBaseUrl` parameter in a Staticman API instance can only take one GitLab URL.  From [project owner's comment in August](https://github.com/eduardoboucas/staticman/pull/219#issuecomment-417657297), I _don't_ think his development instance `dev.staticman.net` would support Framagit.

Here's two instances that I've created for testing Staticman's GitLab support as well as the unmerged [PR 231](https://github.com/eduardoboucas/staticman/pull/231).

| "name" | "public GitLab instance" | "public Framagit instance" |
| --- | --- | --- |
| GitLab instance served | GitLab.com | Framagit |
| `gitlabBaseUrl` | https://gitlab.com | https://framagit.org |
| GitLab Bot | [staticmanlab](https://gitlab.com/staticmanlab) | [staticmanlab1](https://framagit.org/staticmanlab1) |
| `githubBaseUrl` | https://github.com | https://github.com |
| API URL | https://staticman3.herokuapp.com | https://staticman-frama.herokuapp.com |

Both of them are run on a Heroku free dyno, which sleeps after 30 minutes of inactivity and has a 20s wake-up time.

**Comment by VincentTam** [comment]
I've just tested Staticman with this theme on Framagit with my API instance.  Staticman really does its job of getting the form data to the GitLab repo.  As a result, there's no reason to remove this support.

**Pull request closed without merging**
