### PR TITLE
Reduce Theme Specificity

### LINKED ISSUE #109: BUG: Featured Image Scaling
# Feature Request

## Is your feature request related to a problem?
The blog picture is very big in the header of the blog item

## Solution
Option to specify the size of the picture in the blog items of the header.

### LINKED ISSUE #147: BUG: Page extends beyond view port on small devices
i have the same issue. When viewed on mobile device then i see just part of the site or have to zoom out. I even reverted back to the original config.tofl but it did not help. Seems to have something to do with the blogpost content itself. 
You can see this site of another guy who obviously has the same problem but seems not to have noticed it yet: https://jhonmanuncia.me/blog/
Screenshot buggy future imperfect slim

### LINKED ISSUE #151: BUG: Hugo 0.60 removed inline HTML for Markdown Files
I am having problem centering and resizing images in my site. Conventionally, I used Markdown, but as it does not provide these features, I am falling back to CSS, of which I have no knowledge. I still googled it and tried things like 
```
# Attempt 1
<span style="display:block;text-align:centre">![anchor](/img/yolov3_decoding/anchor.png)</span>
 
# Attempt 2
<a href="/img/yolov3_decoding/anchor.png" class="image featured">
  <img src="/img/yolov3_decoding/anchor.png" alt="Pic 1">
</a>

# Attempt 3
<img src="/img/yolov3_decoding/anchor.png?style=centerme" alt="Image" width="800" height="600" style="display: block; margin: 0 auto" />
```

But they don't seem to work.

### LINKED ISSUE #159: FEATURE: add ability to include alt text in featured images
# Feature Request
Please add ability to include alt text in featured images.

## Is your feature request related to a problem?
No problem, just something that I think should be included in some way.

[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]]
Right now, a featured image or images does not include alt text. Likely this is due to the array is represented in the meta information in the markdown files. From my limited understanding so far of SEO best practices, having alt text is very helpful in building a good SEO profile for your site.

## Solution
The images parameter in each markdown file would likely need to be updated to something more complicated, such as an array of key / value pairs to represent both the source and the alt text of each image to be featured. So instead of:
images: ["/img/image1.jpg", "img/image2.jpg"]
it would be something more like:
images: [{ src="/img/image1.jpg", alt="alt text for image1" }, { src="/img/image2.jpg", alt="alt text for image2" }]

The logic behind this appears to be primarily in the ./layouts/_default/featured.html file.

## Alternatives
I don't have any specific implementation preferences, but wanted to primarily ask more about.

### LINKED ISSUE #161: BUG: Truncated formatting of categories in the post meta
# Bug Report

## Describe the bug

Although the category name is small and should easily fit in the allocated space, it is displayed truncated. See the attachment.

The category name is "wandelen".

## To Reproduce

My site is not live yet but I've created a blog post with categories

 -  "wandelen"

and tags

 - "trage tocht"
 - "planken wambuis"
 - "natuurmonumenten"

## Expected behavior

I would expect the category name not be truncated.

## Screenshots

Screenshot 2020-07-13 at 12 07 19
## Environment

 - **Hugo Version:** [0.73]
 - **Browser and Version:** [Safari 13.1.1]
 - **Platform:** [Desktop]

### LINKED ISSUE #163: BUG: Previous/next for blog inconsistent with pagination
# Bug Report

## Describe the bug

The previous/next buttons underneath a blog are in reverse order compared to the pagination. With pagination the left button goes to the previous page (more recent posts) and the right button to the next page (older posts). Underneath a blog page the left button will go to the next (older) article and the right button goes to the previous (newer) article.

## To Reproduce

Visible when multiple blog posts are available that generate at least 3 pages.

## Expected behavior

The left button underneath the blog should go to the newer article, the right button to the older article.

## Screenshots

On the blog index page the order of articles is shown including the previous/next buttons:

Screenshot 2020-07-14 at 07 16 46

The next image shows the buttons underneath the middle article. The order does not match that of the index page:

Screenshot 2020-07-14 at 07 17 02

## Environment

 - **Hugo Version:** [0.73]
 - **Browser and Version:** [Safari 13.1.1]
 - **Platform:** [Desktop + Mobile]
 - **Link to Project:**

### PR DESCRIPTION
**Pull request by pacollins**
## Description

Due to the breadth of this PR, please feel free to comment with anything that you feel is off (even if you aren't sure if it was before or after these changes)

Notes below are in order of commit:

1. **Bloat from extra highlight.js themes has been removed.** The `default` [theme](https://highlightjs.org/static/demo/) is now the default. `dark` was left as an alternative without cdn, but also for future use in dark mode.
    ⚠️ Users that utilize `enableCDN = false` *may* require config.toml adjustments.
2. **Adjusted site templates to reduce [lookup order](https://gohugo.io/templates/lookup-order/) at the theme level.**
   ⚠️ Users that reference the following files in custom templates (`ROOT/layouts`) *may* require adjustment: 
    - `_default/comments.html`
    - ❌`_default/home.html`
    - `_default/list,html`
    - ❌`_default/pagination.html`
    - `_default/single.html`
    - ❌`_default/staticman.html`
    - ❌`partials/pagination.html`
3. **Adjusted i18n to reduce specificity and repetition (particularly with forms).**
    ⚠️ Users that have implemented their own i18n languages, or reference i18n translations in custom templates *may* require adjustment.
    - `postreadingtime --> reading_time`
    - `404_goback --> 404_back`
    - ❌ `category --> [categories] one`
    - ❌ `tag --> [tags] one`
    - `repliestext --> contact_replies`
    - `say_sth --> say_something`
    - `name --> form_name`
    - `email --> form_email`
    - `website --> form_website`
    - `body --> form_body`
    - `no_comment --> nothing_yet`
    - `btn_reset --> reset`
    - `btn_submitted --> submitted`
    - `btn_sumbit[sic] --> submit`
4. **Adjusted and refactored comment classes to reduce specificity and increase efficiency.**
    ⚠️ Users that have a custom template for comments *will* require adjustment if it uses the theme's CSS and JS.
5. **Adjusted `featured`/`images` for posts in response to #109 and replacing #128. See below for screenshots.** `[[images]]` now allows for multiple images for the purposes of OpenGraph tags.
    ⚠️ Users that have front matter that utilize `images` (backwards compatibility for `featured` and associated parameters still remains) will need to adjust from `[images]="SRC"` to the following format:
    ```
    [[images]]
        src = "" // Link to image
        alt = "" // Alt text for image
        stretch = // Optional: See screenshots for referenced values and outcomes
    ```
6. **Original `exampleSite` images had an unknown origin, so they have been changed to known royalty-free images.** Additionally, `exampleSite` and archetype front matter has been adjusted.
7. **Set `exampleSite/config.toml` to allow inline HTML rendering (commit name error) in response to #151.** 
8. **Complete refactor of CSS in response to #147 and the general reduction of specificity.**
    ⚠️ Users with custom CSS *may* need to adjust due to a variety of class name changes and specificity changes.
9. **Add `featuredstretch` parameter to frontmatter for backwards compatibility.** This is the same as `stretch` in 5 above.
10. **Add `imagestretch` global parameter to `.Site.Parameters` to allow a default `stretch` value to be set.**

## Motivation and Context

The overall motivation is to give more power to the user to customize the theme easily.

- Closes #109
- Closes #147
- Closes #151
- Closes #159 
- Closes #161 
- Closes #163 

## Featured Image

The featured image at full size is `880x280` and scales with the page. Images fit vertically into the container. For images that do not fill the whole container, the image is duplicated, stretched, and blurred behind the original.

~~🐞 *Note:* It is a known bug that it does not center vertically, I am still working on that.~~ Bug has been fixed.

image

image

If you do not prefer this look, you can add `stretch` to your front matter. Accepted values are `Horizontal`, `H`, `Vertical`, and `V`, This parameter is not case sensitive.

### `stretch = "horizontal"`

image

### `stretch = "vertical"`

image

### `stretch ="both"`

Since this would distort images (see below), this is not a valid value.

image

## Checklist:

- [x] I have updated the [documentation](https://github.com/pacollins/hugo-future-imperfect-slim/wiki), as applicable.
- [ ] I have updated the `theme.toml`, as applicable.

### CODE REVIEW

**Comment by pra-dan** [comment]
Very happy to see the changes. It would be perfect for the issue #151 if the image could be 
- resized 
- captioned
- Aligned

The first feature is currently achievable using
```
{{< figure src="/img/yolov3_decoding/iou1.jpg" height=400 width=550 >}}
```

The second feature is not currently working. Even on using 
```
{{< figure src="/img/yolov3_decoding/iou1.jpg" caption="Results without IOU" height=400 width=550 >}}
```
The caption is automatically aligned to the left. 
Screenshot from 2020-06-27 09-32-18


The feature is achieved by 
```
<div>
    <img class="marginauto" src="https://media.giphy.com/media/UX4U37Y9mdz3BXNbcA/giphy.gif" alt="centered image" />
</div>
<style>
.marginauto {
    margin: 20px auto 20px;
    display: block;
}
</style>
```
But this is too much code for each image
___
Also, all the 3 can never be implemented together. Please look into this too :man_astronaut: :

**Comment by pacollins** [comment]
Caption should be an easy fix for the built-in shortcode. `figure {text-align: center}` You could even test it by adding it to your `add-on.css`.

That being said, I will add that here.

**Comment by pra-dan** [comment]
But there seems to be no way to resize, caption, and align the image together. Another thing I suggest is to add functionality to give blank lines wherever needed...just for formating purpose. Things get too cluttered at times :family_man_boy_boy:

**Comment by pacollins** [comment]
I see what you mean now, that would be developing a different shortcode. I highly recommend you try it (and then create a PR), its not too difficult and I can assist. [Hugo's docs are pretty detailed[https://gohugo.io/content-management/shortcodes/], and I have detailed my [`fancybox` shortcode pretty well as a reference](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/shortcodes/fancybox.html).

**Comment by pra-dan** [comment]
Ok that seems reasonable. I have absolutely no experience with HTML/CSS but I am willing to learn that soon. It will take some time but I will try my best to add these features :yo_yo:

**Comment by twatzl** [comment]
Hi just tested this and got a few questions/issues

1. is it possible to set stretch behavior of the featured image globally? I think this would make it way easier to migrate for like dozens of blog entries.
2. ~~the stretch="horizontal" in the front matter of a blogpost gets ignored for me~~

nevermind i was using the "old" featured syntax like this
```
+++
...
lang = "en"
featured = "2019-05-12_040.JPG"
featuredalt = ""
featuredpath = "Blog/2019-05-12_tallinn_1"
stretch = "horizontal"
...
```

however with the old stuff i do not get the blurry background
image

for preview i run the following docker command in the root directory of my blog

```
docker run --rm -it -v $PWD:/src -p 1313:1313 -u hugo hugo-builder:0.69.0 hugo server --disableFastRender -w -v --bind=0.0.0.0
```

once changed to the "new" syntax it worked

3.  I have another proposal for how the blog entries could be designed. let me know if i should open a separate ticket for this:

there could be another style option like stretch for compact="true" 

This mode could make more compact blog entries like this:

image
(proudly hacked together with flexbox using waaayyy too much time)

On mobile or for images with high aspect ratio (e.g. panoramas) still the full width could be used.
I am no css expert and have no idea if this is possible, but it could save some space on bigger screens.

**Comment by pacollins** [comment]
>is it possible to set stretch behavior of the featured image globally?

The reason I didn't do this is because that would assume all picture are the same aspect ratio. I guess an option would be to allow you to set a value and then override it with a value in the post. Does that seem reasonable?

>however with the old stuff i do not get the blurry background

I will look at this.

> there could be another style option like stretch for compact="true"

I'm not opposed to the idea, but that doesn't look more compact to me. It just shifts where the image is

**Comment by twatzl** [comment]
> The reason I didn't do this is because that would assume all picture are the same aspect ratio. I guess an option would be to allow you to set a value and then override it with a value in the post. Does that seem reasonable?
Yes. It seems totally reasonable. I missed to write that I meant this as a way to set a default which is used unless something else is specified in the post. 

> I'm not opposed to the idea, but that doesn't look more compact to me. It just shifts where the image is
Well the image and the first paragraph would then be in the same line on large images. Anyway I made a comment at #109 where I provide mockups how i thought it could work, as to not clutter this discussion here too much.

**Comment by pacollins** [comment]
@twatzl - I have added backwards compatibility for the blurred image and stretch under a semantically similar `featuredstretch` to match `featuredalt` and `featuredpath`. Additionally, I have added `.Site.Params.imageStretch` which allows for a site wide default value.

```
  readingTime           = true
  imageStretch          = ""
```

**Comment by pacollins** [comment]
What I did to features.html is not relevant except for the following addition:

        {{ $alt }}

I've included an additional stretch value of "cover" or "c" and added the following to add-on.css:

    .image img.cover {
      object-fit: cover;
      width: 100%;
    }

This will use the full width of the box for the image, place the image in the center of the box and because of the "overflow: hidden" on the .image class the excess is removed. This results in a non-distorted image that covers the complete box.

Screenshot 2020-07-13 at 16 55 30

_Originally posted by @kdbruin in https://github.com/pacollins/hugo-future-imperfect-slim/issues/161#issuecomment-657609576_

**Comment by pacollins** [comment]
@kdbruin - I can either make this commit, or you can if you would like to receive credit.

**Comment by kdbruin** [comment]
No, go ahead and do the commit.

**Comment by twatzl** [comment]
Hi I noticed two more things.
First the text margin now seems to be quite narrow
old (featured image removed with devtools so it fits on one screenshot):
image

new:
image

I think reducing the margin in the title is ok since it makes the title section more compact. Though in the post I would like to see the same margin. The new one just looks like too little margin. 

A simple tutorial in the documentation how to adapt these kind of things would be sufficient I think ;)


The second thing I noticed is that some images do not seem to work properly anymore.
I am using this gallery plugin: https://github.com/liwenyip/hugo-easy-gallery

Actually the images with captions look very awesome, but some of the others are just collapsed:
https://twatzl.eu/blog/2020-04-15_moon_hdr/

Interestingly enough on my local machine they are not quite as broken as on my server.
image

Unfortunately I will not be able to do some further investigation until the weekend. 
Though right now the changes already look quite awesome 👍

**Comment by pacollins** [comment]
I think in a separate PR, I am going to refactor the typography (including the margins that you mention). I have learned more about web typography, so I think that the site's original sizings are less than ideal.

I will investigate the images issue further. The site has native support for [fancybox](http://fancyapps.com/fancybox/3/), but I have become skeptical about its efficiency. I will look into that hugo-based solution you have linked!

**Comment by twatzl** [comment]
I think I found the culprit. It seems that
```
  width: fit-content;
```
does not do what it advertises ;) 
When removing this from figure it works again. 

I never really used fancybox because I am not a web guy and I could not find any documentation here in this repo on how images are supposed to work. Maybe could be a topic for another issue.

**Comment by twatzl** [comment]
So after wasting way too much of my lifetime with css I got a somewhat satisfying solution.
I used flexbox a lot. Actually only had to remove 2 lines from your scss file to make everything work. I think it looks quite nice, only on mobile devices it does not look as expected, however that is an issue for another day.

Here is what I changed. I did it by trial and error. Maybe it helps you in finding a generic solution.
[gallery-css-fix.patch.txt](https://github.com/pacollins/hugo-future-imperfect-slim/files/4927426/gallery-css-fix.patch.txt)
[css-figure-fix.patch.txt](https://github.com/pacollins/hugo-future-imperfect-slim/files/4927427/css-figure-fix.patch.txt)

**Comment by pacollins** [comment]
If that is the case, I am going to tiny some of the documentation related items. My hope will be to merge tomorrow.

**Comment by tmswfrk** [comment]
hey, sorry I haven't mentioned this sooner, but is there a particular stretch param that we can include here to make the image look as it used to? I'm unable to determine how to get my single featured image without the additional --bg-image class coming through and changing the way my site looks. I tried implementing the `featured` and `featured alt` params that I see are available, but the same css class structure is coming through. I'm hoping not to have to write my own partial for this one :) Thanks.

**Comment by pacollins** [comment]
Check out #182 and `removeBlur = true`.

**Comment by tmswfrk** [comment]
Thanks for responding so quickly, but this still doesn't revert the change for my site. I have images now that, while still considerably larger in resolution than they are being fitted (fine by me), they're still being reduced in size and are being matched in size to each other. The regular images that I have elsewhere in my posts look unchanged. I'm not enough of a UI person to understand what CSS properties are affecting this, but I have noticed that when I turn off `position: absolute` style from the img tag, and then remove the `padding-bottom: 33%` style from the a href tag just above it, the image appears as I remember it. Is there something here that I'm missing that you can potentially help me out with?

Looking through git, I see that this padding-bottom and position value are both configured within the `assets/scss/main.scss` file, but I don't know if they were changed recently in the #182 commit you referred to here. I think there's something else here that I'm missing. I can provide screenshots if you'd like. Thanks.

**Comment by pacollins** [comment]
Screenshots are great, a live example is even better (albeit sometimes not a reasonable request).

`position: absolute` allows the image to appear over the blurred image.

`padding-bottom: 33%` maintains the aspect ratio. On my site, it looks like I adjust the header image to be shorter and wider. `padding-bottom: 35%` seems to revert it back to the original aspect ratio. I am trying to remember why I did this exactly.

See the left and right sides on the images below:

# 33%
image

#35%
image

**Comment by tmswfrk** [comment]
Thanks for that. My issue appears to be a bit more significant. See the "original" and the "new" files attached. Both were zoomed out to 67% so that I could showcase the differences a bit more obviously. Seems that most of the featured images (including the original logo) are now appearing to be significantly reduced with additional, unneeded whitespace / padding around them.
Original
New

Original site that showcases the previous code is at https://www.bicyclewatercooler.com while the new one is still locally staged for now. I'd have to push up a duplicate site to Azure to showcase it a bit more obviously for you. Thanks. I'll keep looking into this one myself, too.

**Comment by pacollins** [comment]
I see.

To ensure consistent design and make the blurred background work, I forced
the image to maintain the aspect ratio. The container has a set height and
the image is set to fill that height. Since your images are tall, they are
being squished down to fit the container. In your custom css, you want the
container height to be unset.

As for the logo image - in not sure. I'll look into that.

**Comment by tmswfrk** [comment]
So given that this is more of a side project of mine and that this has been causing me enough undue stress to the point where I'm not writing any more content, I'm going to revert back to an older commit and continue in a detached state. This whole thing is reminding me just how much I despise dealing with CSS.

If you have any specifics for me to help me out (the container point earlier did not seem to help, I think the issue here is more as to the order in which some of these styles are being applied from my best guess), please let me know and I'll do what I can to get back up to HEAD on this repo. Thanks.

**Comment by dotMavriQ** [comment]
If you happen to be a big dumb like me, and forked this theme a good while back before these improvements and changes to the front matter. There's a conversion script I can provide here that will help. [Link to GitLab](https://gitlab.com/DotMavriq/nottz)

**Pull request merged**
