### PR TITLE
Added italian

### PR DESCRIPTION
**Pull request by Fastbyte01**
## Description

Added the italian translation.

## Motivation and Context

Added the italian language for italian people that want to use the theme.

### CODE REVIEW

**Comment by pacollins** [comment]
Thanks for this!

We actually have a PR (#154) that reformats the i18n and changes some of the names. [Here is the new template](https://github.com/pacollins/hugo-future-imperfect-slim/blob/reduce-specificity/i18n/en.toml). Included with this, I modified some of the phrases slightly. I would love to just go ahead and take advantage of your expertise to ensure the phrasing is still accurate.

Would you mind adjusting this and then we can merge it there? I have already adjusted the target branch of this PR.

**Comment by Fastbyte01** [comment]
> Thanks for this!
> 
> We actually have a PR (#154) that reformats the i18n and changes some of the names. [Here is the new template](https://github.com/pacollins/hugo-future-imperfect-slim/blob/reduce-specificity/i18n/en.toml). Included with this, I modified some of the phrases slightly. I would love to just go ahead and take advantage of your expertise to ensure the phrasing is still accurate.
> 
> Would you mind adjusting this and then we can merge it there? I have already adjusted the target branch of this PR.

Yes no problem

**Comment by pacollins** [comment]
No rush @Fastbyte01 - Just checking to make sure all is going well! We are beginning to finish up the other PR, so I would love it if we could get yours in before that!

**Comment by pacollins** [comment]
This was an accidental merge and has been reverted. If you could please make the changes and make a new PR, that would be great!

**Pull request merged**
