### PR TITLE
Fixes comments.html to respect the staticman boolean in [params.staticman]

### PR DESCRIPTION
**Pull request by rmbolger**
## Description

Changes the reference to the staticman boolean from `.Site.Params.staticman` to `.Site.Params.staticman.staticman`.

## Motivation and Context

This change addresses issue #59 and fixes comments.html to respect the staticman boolean in [params.staticman].

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have read the [Contributing Document](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md).
- [X] My code follows the [code style](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md#Style-Guide) of this project.
- [ ] My change requires a change to the [documentation](https://github.com/pacollins/hugo-future-imperfect-slim/wiki).
- [ ] I have updated the documentation, including `theme.toml`, accordingly.

### CODE REVIEW

**Comment by rmbolger** [comment]
I don't have a preference either way. But won't that be a breaking change for existing sites? Or does it not count because it's already broken?

**Comment by VincentTam** [comment]
@rmbolger I'm finding a way to push to this PR from terminal.

```diff
diff --git a/layouts/post/comments.html b/layouts/post/comments.html
index 81ab9fb..799296c 100644
--- a/layouts/post/comments.html
+++ b/layouts/post/comments.html
@@ -2,7 +2,9 @@
     <article class="post">
         {{ template "_internal/disqus.html" . }}
     </article>
-{{ else if .Site.Params.staticman.staticman }}
+
+{{/* Backwards compatibility for deprecated parameter ".Site.Params.staticman.staticman" */}}
+{{ else if or .Site.Params.staticman.enabled .Site.Params.staticman.staticman }}
     <article class="post">
       {{ .Render "staticman" }}
     </article>
diff --git a/layouts/post/staticman.html b/layouts/post/staticman.html
index 66fa9a9..8f8279b 100644
--- a/layouts/post/staticman.html
+++ b/layouts/post/staticman.html
@@ -1,6 +1,6 @@
 <h2>Say something</h2>
 {{ with .Site.Params.staticman }}
-  <form class="post-new-comment" method="POST" action="https://{{ .api }}/v3/entry/{{ .gitprovider }}/{{ .username }}/{{ .repo }}/{{ .branch }}/comments">
+  <form class="post-new-comment" method="POST" action="https://{{ .api | default "api.staticman.net" }}/v3/entry/{{ .gitprovider }}/{{ .username }}/{{ .repo }}/{{ .branch }}/comments">
 {{ end }}
     <input type="hidden" name="options[redirect]" value="{{ .Permalink }}">
     <input type="hidden" name="options[entryId]" value="{{ .File.UniqueID }}">
```

**Comment by rmbolger** [comment]
You should just be able to clone my repo as if it were yours and push to it.

**Comment by rmbolger** [comment]
Looks good to me.

**Comment by VincentTam** [comment]
> You should just be able to clone my repo as if it were yours and push to it.

@rmbolger Thanks for your tip.  More precisely, I added the SSH URL for your repo to my list of remotes, and I pushed directly to the branch.  The only thing added to my repo is the additional Git references and the Git objects in this PR.

> Looks good to me

Thanks for feedback. :+1:

**Pull request merged**
