### PR TITLE
Added back CC-BY 3.0 to original theme

### LINKED ISSUE #47: Licensing issue
https://html5up.net/license

Your LICENSE file makes it appear as though the original theme from HTML5Up was licensed under Expat/X11 though it was not and all users of remixes of the actual license (linked above) must give credit as required by the licensor.

### PR DESCRIPTION
**Pull request by VincentTam**
## Description

Added back the [CC-BY 3.0 license](https://html5up.net/license) of [HTML5 UP's original theme](http://html5up.net/future-imperfect).

The format of LICENSE.md has been taken from [Beautiful Jekyll](https://github.com/daattali/beautiful-jekyll/blob/master/LICENSE) and [Beautiful Hugo](https://github.com/halogenica/beautifulhugo/blob/master/LICENSE).

## Motivation and Context

To resolve #47.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the [Contributing Document](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the [code style](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md#Style-Guide) of this project.
- [ ] My change requires a change to the [documentation](https://github.com/pacollins/hugo-future-imperfect-slim/wiki).
- [ ] I have updated the documentation, including `theme.toml`, accordingly.

### CODE REVIEW

**Comment by VincentTam** [comment]
> In case it helps, I found an example of a CC BY 3.0 Unported website created by CC people for the purpose of helping people figure out how to properly attribute CC work: http://openattribute.com

Thanks for :radio_button: , but the :link: isn't working: https://addons.mozilla.org/en-US/firefox/addon/openattribute/.

Anyways, it's @pacollins to decide.

**Comment by pacollins** [comment]
The original version didn't include this, so it wasn't a concern for me. That being said, this is a good adjustment to make.

**Comment by balibebas** [comment]
If by _original version_ you're referring to the non-slim adaptation of the original work the statement "they didn't so I don't have to" if a Tu Quoque fallacy. As it stands "original version" is not clear.

**Comment by pacollins** [comment]
> If by _original version_ you're referring to the non-slim adaptation of the original work the statement "they didn't so I don't have to" if a Tu Quoque fallacy. As it stands "original version" is not clear.

You are being overtly aggressive with your tone and it is not appealing to me. It isn't a Tu Quoque fallacy. It is the fact that the version that this is adapted from did not include it. It is assumed that they did everything they needed to do. There is a reason the license protects adaptations of adaptations. I said that the adjustment was a good one to make. Take it as it is. Currently (barring the URI and Correct License) our attribution is actually more than what is prescribed in the license.

**Pull request merged**
