### PR TITLE
Added support for Dutch language

### LINKED ISSUE #171: BUG: Next/previous links not translated
# Bug Report

## Describe the bug

The next/previous texts on the list template page are hardcoded instead of using the defined i18n constants.

## Fix

```
diff --git a/layouts/_default/list.html b/layouts/_default/list.html
index 108261c..3ad0c15 100644
--- a/layouts/_default/list.html
+++ b/layouts/_default/list.html
@@ -5,10 +5,10 @@
   {{ end }}
   <div class="pagination">
     {{ if .Paginator.HasPrev }}
-      <a href="{{ .Paginator.Prev.URL }}" class="button left"><span>Previous</span></a>
+      <a href="{{ .Paginator.Prev.URL }}" class="button left"><span>{{ i18n "previous_page" }}</span></a>
     {{ end }}
     {{ if .Paginator.HasNext }}
-      <a href="{{ .Paginator.Next.URL }}" class="button right"><span>Next</span></a>
+      <a href="{{ .Paginator.Next.URL }}" class="button right"><span>{{ i18n "next_page" }}</span></a>
     {{ end }}
   </div>
 {{ end }}
```

### PR DESCRIPTION
**Pull request by kdbruin**
## Description

I've added support for the Dutch language. To support the proper date format I've changed the way the date is formatted using a new template and select the formatting based on the current site language.

## Motivation and Context

I'm Dutch ;)

Closes #171

## Checklist:

- [ ] I have updated the [documentation](https://github.com/pacollins/hugo-future-imperfect-slim/wiki), as applicable.
- [ ] I have updated the `theme.toml`, as applicable.
- [X] I have updated the `exampleSite/config.toml` to include the new language

### CODE REVIEW

**Comment by pacollins** [comment]
Thanks for this! Thinking long term (if another language uses this format), I wonder if there is a way to "nest" months and date format with i18n. Would you mind investigating?

Can you go ahead and include #171 with this fix? Weird oversight on my part.

**Comment by kdbruin** [comment]
I've searched for ways to get the date formatted properly and using some lookup table for the months is the only way I've seen it done. Also, there is no multi language support for the `.Render` function as that would make it really easy to add support for a formatted date in another language.

But I will look into this some more and also add the fix from #171 to this.

**Comment by kdbruin** [comment]
I've looked a bit more at content views and it is possible to use language specific files. I've changed the implementation to 2 files instead of a conditional statement.

**Comment by pacollins** [comment]
Thank you for your assistance and humoring me on the flexibility! I will do some testing and then confirm!

**Comment by kdbruin** [comment]
Go ahead, merge the changes.

**Pull request merged**
