### PR TITLE
⚑ → Language list

### LINKED ISSUE #61: FEATURE: Switch from flags to language names
# Bug Report

## Problem description
I am from Austria. Although we speak German here our language and culture is different from Germany in a few aspects. 

Our official locale as far as i know is de-AT, but when I use that for the translation it tries to load the flag `flag-icon-de-at` which does not exist.

## Solution
A configuration possibility to configure the flag icon independently could solve the issue.

i.e.
```
flag: at
```

## Workaround
I just use 'at' now as locale. Now the flag works, but I am not sure what else I broke in the process of doing so.

### PR DESCRIPTION
**Pull request by VincentTam**
## Description

Replaced flags with language name with code.

## Motivation and Context

Resolve #61.

## Screenshots (if appropriate):

Screenshot_2019-08-22 Creating a New Theme

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the [Contributing Document](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the [code style](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md#Style-Guide) of this project.
- [ ] My change requires a change to the [documentation](https://github.com/pacollins/hugo-future-imperfect-slim/wiki).
- [ ] I have updated the documentation, including `theme.toml`, accordingly.

### CODE REVIEW

**Comment by pacollins** [comment]
Switched to keep the design the same (square in the navbar versus the full word). Only issue I see is when we have lang and locale code, which would make it 5 characters. But I figured that is such an edge case I'm fine with it. Still working on the CSS. I might do a quick one here and restructure the `.flyout-menu` in another PR.

**Comment by pacollins** [comment]
Done styling what is related to this PR. I force-pushed to try and clear the merge conflict manually (caused by #78) by adding the "newer" CSS and it still didn't like it, but I was able to do it here easily. Just something to note - having two css related PRs at a time with the pipe is going to be a little annoying since the conflict is hard to find and fix.

**Comment by VincentTam** [comment]
> Done styling what is related to this PR. I force-pushed to try and clear the merge conflict manually (caused by #78) by adding the "newer" CSS and it still didn't like it, but I was able to do it here easily.  Just something to note - having two css related PRs at a time with the pipe is going to be a little annoying since the conflict is hard to find and fix.

the fact that everything goes to one same big SCSS file might be contribute to the merge conflict, since in every diff hunk, the neighbouring three lines of each changed line are displayed.  When two areas overlap, merge conflict would possibly occur.  CSS is not (yet?) my thing, so I couldn't comment on the actual SCSS.  What I put in https://github.com/pacollins/hugo-future-imperfect-slim/pull/80/files/65e4a5d904bedc0ac0a3822e8a67e9e367a3883f#diff-bbefc3ad9404805c599babc090218242 is simply a workaround to produce good-looking (IMO, at least) screenshots.

The actual rules for determining pulls and pushes can be much more difficult than we know, but I know that you've tried your best to push your work.

To revert merges, you might try [`git revert [commit hash] -m [1|2]`](https://stackoverflow.com/a/7100005). In the case of divergence of branches, you might try `git pull --rebase` or even `git rebase -i` to linearise the commit history graph so as to [keep Git history down](https://discourse.gohugo.io/t/hugo-themes-donts/17714?u=vincenttam).

In case of divergence for the same file, you might want to record your changes first by `git diff > my.[diff|patch]` and hard reset to a previous verison by `git checkout [commit hash] -- conflictFile`.  The double hyphen limits the scope of the Git command.  Either `git apply -3 my.patch`, `git am` or `patch -p1 < my.diff` would do.  In the perfect case, choose the first one.  I've not tested the 2nd one.  In a more complicated case, use the 3rd one.

**Comment by pacollins** [comment]
>the fact that everything goes to one same big SCSS file might be contribute to the merge conflict, since in every diff hunk, the neighbouring three lines of each changed line are displayed. 

#66 Since we are now using pipes, it might be worth while to split it into multiple scss files for clarity. I will explore this.

>To revert merges, you might try git revert [commit hash] -m [1|2]. In the case of divergence of branches, you might try git pull --rebase or even git rebase -i to linearise the commit history graph so as to keep Git history down.
Thanks for increasing my git knowledge. Those two concepts have always been muddy for me.

I will try to go back and adjust this.

**Comment by VincentTam** [comment]
I think we don't need `assets/scss/main.min.css`, which has been introduced in #78?  Compiled and compressed main CSS is already found under `exampleSite/resources/_gen`.

> Thanks for increasing my git knowledge. Those two concepts have always been muddy for me.
I will try to go back and adjust this.

Given that you've already forced pushed stuff, let's keep its *status quo*.  [Oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) can help the Git indexing: https://www.git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Zsh, while [tldr](https://tldr.sh/)'s abridged man pages are good enough for usual purposes.

**Comment by pacollins** [comment]
> I think we don't need `assets/scss/main.min.css`, which has been introduced in #78? Compiled and compressed main CSS is already found under `exampleSite/resources/_gen`.

Good Catch! I have an auto-compiler set up that I forgot to remove when we switched to pipes!

**Comment by pacollins** [comment]
If you are good, this is ready to be merged.

**Pull request merged**
