### PR TITLE
Add Strava

### LINKED ISSUE #139: FEATURE: add "Strava" social network icon and quick link
# Feature Request

## Is your feature request related to a problem?
Not a problem at all, but given how many other social networks are included here, I'd love to have the option to add Strava (specifically a social platform for cycling, running, and other sports) as a configurable option.

## Solution
Should be just mimicking existing references for LinkedIn, Instagram, or Vimeo to add a new one that builds a link to a particular user's Strava athlete page. As an example, I could provide user "123456" to the Strava key in the config.toml file and then have it build a link to the athlete page at https://www.strava.com/athletes/123456. 

## Alternatives
No alternative really. Just a feature request.

## Additional Context
Just mimic the same functionality as elsewhere.

### PR DESCRIPTION
**Pull request by pacollins**
## Description

Added Strava to Config.

Though I am wondering if the social icons should be cleaned with an easier way for users to add the icons they need. An example would be to replace the social part of the current `config.toml` with:

```
social-media = [
    [service-name, service-url, account-name, icon].
    ["Github", "github.com", "pacollins", "fab fa-github"]
]

{{ range .Site.social-media }}
    <li><a href="{{ index . 1}}/{{ index . 2}}" target="_blank" rel="noopener" title="{{ index . 0}}" class="{{ index . 3}}"></a></li>
{{ end }}
```

The benefits of this are:

1. Users can can icons without needing edits to the entire theme.
2. The total size of the theme would decrease by moving customization to the config
3. Users could also re-order the icons as they saw fit.

The issues of this are:

1. This would be a theme-breaking change.
2. It is an added layer of complexity.

To assist with added complexity, the `config.toml` could come with the already-included sites, but have templating that requires a username before it will populate on the live site.

## Motivation and Context

Fixes #139

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have read the [Contributing Document](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md).
- [X] My code follows the [code style](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md#Style-Guide) of this project.
- [X] My change requires a change to the [documentation](https://github.com/pacollins/hugo-future-imperfect-slim/wiki).
- [X] I have updated the documentation, including `theme.toml`, accordingly.

### CODE REVIEW

**Comment by pacollins** [comment]
I guess, in theory, we could leave this as backwards compatible but give notice that we are going to remove it.

**Comment by pacollins** [comment]
Working Example:

config.toml:
```
[params.social]
  sites = [
    ["Github","github.com","fab fa-github","pacollins"],
    ["Facebook","facebook.com","fab fa-facebook","example"],
    ["Instagram","instagram.com","fab fa-instagram", ""]
  ]
```

site-intro.html:
```
<ul class="socnet-icons">
    {{ if .Site.Params.intro.rssIntro }}{{ partial "rss-icon" . }}{{ end }}
    {{ range .Site.Params.social.sites }}
        {{ if and (gt (len (index . 3)) 0) (eq (len .) 4) }}
            <li><a href="{{ path.Join "https://" (index . 1) (index . 3) }}" target="_blank" rel="noopener" title="{{ index . 0}}" class="{{ index . 2}}"></a></li>
        {{ end }}
    {{ end }}
</ul>
```

Result: 
image

**Comment by tmswfrk** [comment]
I'm pretty new to Hugo and am not a front end guy, but I think the scope creep here is a bit more than I had planned for with this ask :) It's not a bad idea, but I think the implementation here is crossing the boundaries a bit when it comes to separation of concerns. I shouldn't have to understand which javascript (I assume it's javascript) class I need at the toml file location to link it to my social media link. I'd be concerned about making this generally too complicated, which may make your theme a little less user friendly to those of us wanting to do more than Wordpress but aren't full time developers. 

Also, the array that you've dictated in the toml example isn't guaranteed to be in the same order each time, from what I've read about online (it's more of an unordered set than a traditional array).

So unless you really want to go this route with your theme, I'd maybe keep things in the way that they are (with the strava addition of course) for now until you decide to make the larger, backward compatible change.

**Comment by pacollins** [comment]
Haha! Sorry about increasing the scope on you. The only reason I broadened it was because we get lots of small requests like this which are tedious and increase overall theme bloat (for example, we support QQ, but that is a China-only service). It sounds like the main issue you have is getting the brand icon class. If I better documented that you find the icon you want [here on FontAwesome](https://fontawesome.com/icons?d=gallery&s=brands) and copy its class code (see below), would that alleviate your concern?

image

That being said, the end-user is already being asked to do this in the config for the nav-bar.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/a3c7c7ce42e854f2534e79229ddb570b9518b85d/exampleSite/config.toml#L115-123

**Comment by pacollins** [comment]
I am going to go ahead and merge this for you, but I would like your comment on my last post when you have the chance, @tmswfrk.

**Comment by tmswfrk** [comment]
Hey, so thanks for the info. I see a bit more as to what you're talking about now, after poking through some code. It's up to you, since you've seen these requests come in, but something like a static content generator, in my view, should be pretty simple for the most part. I think adding an abstraction layer like this, while totally reasonable, may be unnecessarily complicating things. But, if you provide enough documentation on it, I think you may be fine, also. 

Only issue I need to bring to your attention is that the ordering in my config.toml file is not being respected. I'm pretty positive it's due to your call of `range .Site.Params.social.sites` - in most cases, a range function like this does not guarantee ordering when it comes to an array / slice structure, and you're bound on how the underlying compiler decides to hash the keys into memory.

**Pull request merged**
